DROP TABLE TB_MAINIMG;

DROP TABLE TB_EVENT_COMMENT;
DROP TABLE TB_REPORT;
DROP TABLE TB_INQUIRY;
DROP TABLE TB_NOTICE;

DROP TABLE TB_EVENT;

DROP TABLE TB_CATEGORY;
DROP TABLE TB_CATEGORY_THEME;
DROP TABLE TB_CATEGORY_KIND;
DROP TABLE TB_CATEGORY_TOOL;
DROP TABLE TB_CATEGORY_STEP;
DROP TABLE TB_CATEGORY_NATION;
DROP TABLE TB_CATEGORY_INGREDIENT;


DROP TABLE TB_COOKING_ORDER_IMG;
DROP TABLE TB_REVIEW;
DROP TABLE TB_COMMENT;
DROP TABLE TB_INGREDIENT;
DROP TABLE TB_INGRE_CLASS;
DROP TABLE TB_COOKING_ORDER;

DROP TABLE TB_MEM_ALLERGY;
DROP TABLE TB_WISHLIST;
DROP TABLE TB_ALLERGY;

DROP TABLE TB_RECIPE;

DROP TABLE TB_MEMBER;

DROP SEQUENCE SEQ_MEM_NO;
DROP SEQUENCE SEQ_RECIPE_NO;
DROP SEQUENCE SEQ_CO_NO;
DROP SEQUENCE SEQ_COM_NO;
DROP SEQUENCE SEQ_REV_NO;
DROP SEQUENCE SEQ_INGRE_NO;
DROP SEQUENCE SEQ_ING_C_NO;
DROP SEQUENCE SEQ_ALG_NO;
DROP SEQUENCE SEQ_C_NAT_NO;
DROP SEQUENCE SEQ_C_STEP_NO;
DROP SEQUENCE SEQ_C_TOOL_NO;
DROP SEQUENCE SEQ_C_KIND_NO;
DROP SEQUENCE SEQ_C_THEME_NO;
DROP SEQUENCE SEQ_C_INGRE_NO;
DROP SEQUENCE SEQ_MAINIMG_NO;
DROP SEQUENCE SEQ_REP_NO;
DROP SEQUENCE SEQ_INQ_NO;
DROP SEQUENCE SEQ_NOTICE_NO;
DROP SEQUENCE SEQ_EVENT_NO;
DROP SEQUENCE SEQ_EVENT_COM_NO;



CREATE SEQUENCE SEQ_RECIPE_NO;
CREATE SEQUENCE SEQ_CO_NO;
CREATE SEQUENCE SEQ_COM_NO;
CREATE SEQUENCE SEQ_REV_NO;
CREATE SEQUENCE SEQ_ING_C_NO;
CREATE SEQUENCE SEQ_INGRE_NO;
CREATE SEQUENCE SEQ_MEM_NO;
CREATE SEQUENCE SEQ_ALG_NO;
CREATE SEQUENCE SEQ_C_NAT_NO;
CREATE SEQUENCE SEQ_C_STEP_NO;
CREATE SEQUENCE SEQ_C_TOOL_NO;
CREATE SEQUENCE SEQ_C_KIND_NO;
CREATE SEQUENCE SEQ_C_THEME_NO;
CREATE SEQUENCE SEQ_C_INGRE_NO;
CREATE SEQUENCE SEQ_MAINIMG_NO;
CREATE SEQUENCE SEQ_REP_NO;
CREATE SEQUENCE SEQ_INQ_NO;
CREATE SEQUENCE SEQ_NOTICE_NO;
CREATE SEQUENCE SEQ_EVENT_NO;
CREATE SEQUENCE SEQ_EVENT_COM_NO;

CREATE TABLE TB_MEMBER (
   MEM_NO NUMBER PRIMARY KEY,
   MEM_ID VARCHAR2(60) NOT NULL UNIQUE,
   MEM_PWD VARCHAR2(20) NOT NULL,
   NICKNAME VARCHAR2(60) NOT NULL UNIQUE,
   MEM_NAME VARCHAR2(20) NOT NULL,
   PHONE VARCHAR2(15) NOT NULL,
   WARNING_COUNT NUMBER DEFAULT 0,
   MEM_IMG VARCHAR2(300),
   MEM_STATUS CHAR(1) DEFAULT 'Y' CHECK (MEM_STATUS IN ('Y', 'N'))
);

CREATE TABLE TB_RECIPE (
        RECIPE_NO NUMBER CONSTRAINT RECIPE_PK PRIMARY KEY,
        RECIPE_NAME VARCHAR2(100) CONSTRAINT RECIPE_NM_NN NOT NULL,
        RECIPE_TAG VARCHAR2(100) CONSTRAINT RECIPE_TAG_NN NOT NULL,
        RECIPE_VIDEO VARCHAR2(300),
        RECIPE_DIFFICULTY CHAR(3) CHECK(RECIPE_DIFFICULTY IN ('상', '중', '하')) NOT NULL,
        RECIPE_PERSON NUMBER CONSTRAINT RECIPE_PERSON_NN NOT NULL,
        RECIPE_TIME NUMBER CONSTRAINT RECIPE_TIME_NN NOT NULL,
        RECIPE_DATE DATE DEFAULT SYSDATE NOT NULL,
        MEM_NO NUMBER REFERENCES TB_MEMBER ON DELETE CASCADE NOT NULL,
        RECIPE_PIC VARCHAR2(300) CONSTRAINT RECIPE_PIC_NN NOT NULL,
        RECIPE_VIEWS NUMBER DEFAULT 0 CONSTRAINT RECIPE_VIEWS_NN NOT NULL,
        RECIPE_STATUS CHAR(1) DEFAULT 'Y' CHECK(RECIPE_STATUS IN('Y', 'N')) NOT NULL
);
CREATE TABLE TB_ALLERGY (
   ALG_NO VARCHAR2(10) PRIMARY KEY,
   ALG_NAME VARCHAR2(50) NOT NULL
);
CREATE TABLE TB_WISHLIST (
	MEM_NO NUMBER REFERENCES TB_MEMBER ON DELETE CASCADE,
    RECIPE_NO NUMBER REFERENCES TB_RECIPE ON DELETE CASCADE,
    CONSTRAINT WISHLIST_PK PRIMARY KEY(MEM_NO,RECIPE_NO)
);
CREATE TABLE TB_MEM_ALLERGY (
   MEM_NO NUMBER REFERENCES TB_MEMBER ON DELETE CASCADE,
   ALG_NO VARCHAR2(10) REFERENCES TB_ALLERGY ON DELETE CASCADE,
   CONSTRAINT ALLERGY_PK PRIMARY KEY(MEM_NO,ALG_NO)
);
CREATE TABLE TB_COOKING_ORDER (
    CO_NO NUMBER CONSTRAINT CO_NO_PK PRIMARY KEY,
    RECIPE_NO NUMBER REFERENCES TB_RECIPE ON DELETE CASCADE,
    CO_STEP  VARCHAR2(10) CONSTRAINT CO_STEP_NN NOT NULL,
    CO_CONTENT VARCHAR2(300) CONSTRAINT CONTENT_NN NOT NULL
);
   
-- 테이블 생성(TB_INGRE_CLASS)
CREATE TABLE TB_INGRE_CLASS (
    INGRE_C_NO NUMBER PRIMARY KEY,
    RECIPE_NO NUMBER REFERENCES TB_RECIPE ON DELETE CASCADE,
    INGRE_C_NAME VARCHAR2(50) DEFAULT '재료' NOT NULL
);

-- 테이블 생성(TB_INGREDIENT)
CREATE TABLE TB_INGREDIENT (
    INGRE_NO NUMBER PRIMARY KEY,
    INGRE_C_NO NUMBER REFERENCES TB_INGRE_CLASS,
    INGRE_NAME VARCHAR2(60) NOT NULL,
    INGRE_AMOUNT VARCHAR2(30) NOT NULL
);

-- 테이블 생성 (TB_COMMENT)
CREATE TABLE TB_COMMENT (
    COM_NO NUMBER CONSTRAINT COM_NO_PK PRIMARY KEY,
    RECIPE_NO NUMBER REFERENCES TB_RECIPE ON DELETE CASCADE,
    COM_CONTENT VARCHAR2(300) CONSTRAINT COM_CONTENT_NN NOT NULL,
    MEM_NO NUMBER REFERENCES TB_MEMBER ON DELETE CASCADE NOT NULL,
    COM_DATE DATE DEFAULT SYSDATE,
    COM_STATUS CHAR(1) DEFAULT 'Y' CHECK (COM_STATUS IN ('Y', 'N'))
);
   
-- 테이블 생성(TB_REVIEW)
CREATE TABLE TB_REVIEW (
    REV_NO NUMBER CONSTRAINT REV_NO_PK PRIMARY KEY,
    RECIPE_NO NUMBER REFERENCES TB_RECIPE ON DELETE CASCADE,
    REV_CONTENT VARCHAR2(1000) CONSTRAINT REV_CONTENT_NN NOT NULL,
    REV_IMG VARCHAR2(300) CONSTRAINT REV_IMG_NN NOT NULL,
    MEM_NO NUMBER REFERENCES TB_MEMBER ON DELETE CASCADE NOT NULL,
    REV_DATE DATE DEFAULT SYSDATE,
    REV_STATUS CHAR(1) DEFAULT 'Y' CHECK (REV_STATUS IN ('Y', 'N'))
);
   
-- 테이블 생성 (TB_COOKING_ORDER_IMG)
CREATE TABLE TB_COOKING_ORDER_IMG (
    CO_NO NUMBER REFERENCES TB_COOKING_ORDER ON DELETE CASCADE,
    ORDIMG_IMGURL VARCHAR2(300) CONSTRAINT ORDIMG_NN NOT NULL
);

CREATE TABLE TB_CATEGORY_NATION (
   C_NAT_NO VARCHAR2(10) CONSTRAINT C_NAT_NO_PK PRIMARY KEY,
   C_NAT_NAME VARCHAR2(60) NOT NULL
);

-- 테이블 생성하기(카테고리-방법별)
CREATE TABLE TB_CATEGORY_STEP (
   C_STEP_NO VARCHAR2(10) CONSTRAINT C_STEP_NO_PK PRIMARY KEY,
   C_STEP_NAME VARCHAR2(60) NOT NULL
);

-- 테이블 생성하기(카테고리-도구별)
CREATE TABLE TB_CATEGORY_TOOL (
   C_TOOL_NO VARCHAR2(10) CONSTRAINT C_TOOL_NO_PK PRIMARY KEY,
   C_TOOL_NAME VARCHAR2(60) NULL
);

-- 테이블 생성하기(카테고리-종류별)
CREATE TABLE "TB_CATEGORY_KIND" (
   C_KIND_NO VARCHAR2(10) CONSTRAINT C_KIND_NO PRIMARY KEY,
   C_KIND_NAME VARCHAR2(60) NOT NULL
);

-- 테이블 생성하기(카테고리-테마별)
CREATE TABLE TB_CATEGORY_THEME (
   C_THEME_NO VARCHAR2(10) CONSTRAINT C_THEME_NO_PK PRIMARY KEY,
   C_THEME_NAME VARCHAR2(60) NOT NULL
);

-- 테이블 생성하기(카테고리-재료별)
CREATE TABLE TB_CATEGORY_INGREDIENT (
   C_INGRE_NO VARCHAR2(10) CONSTRAINT C_INGRE_NO_PK PRIMARY KEY,
   C_INGRE_NAME VARCHAR2(60) NOT NULL
);


-- 테이블 생성하기(카테고리)
CREATE TABLE TB_CATEGORY (
   RECIPE_NO NUMBER REFERENCES TB_RECIPE ON DELETE CASCADE,
   C_NAT_NO VARCHAR2(10) REFERENCES TB_CATEGORY_NATION ON DELETE CASCADE,
   C_STEP_NO VARCHAR2(10) REFERENCES TB_CATEGORY_STEP ON DELETE CASCADE,
   C_TOOL_NO VARCHAR2(10) REFERENCES TB_CATEGORY_TOOL ON DELETE CASCADE,
   C_KIND_NO VARCHAR2(10) REFERENCES TB_CATEGORY_KIND ON DELETE CASCADE,
   C_THEME_NO VARCHAR2(10) REFERENCES TB_CATEGORY_THEME ON DELETE CASCADE,
   C_INGRE_NO VARCHAR2(10) REFERENCES TB_CATEGORY_INGREDIENT ON DELETE CASCADE
);

CREATE TABLE TB_NOTICE (
   NOTICE_NO NUMBER CONSTRAINT NOTICE_NO_PK PRIMARY KEY,
   NOTICE_NAME VARCHAR2(100) NOT NULL,
   NOTICE_CONTENTS VARCHAR2(2000) NOT NULL,
   NOTICE_DATE DATE DEFAULT SYSDATE NOT NULL,
   NOTICE_CLSFC VARCHAR2(20) NOT NULL,
   NOTICE_STATUS CHAR(1) DEFAULT 'Y' CHECK(NOTICE_STATUS IN('Y','N'))   NOT NULL
);

CREATE TABLE TB_EVENT (
   EVENT_NO NUMBER CONSTRAINT EVENT_NO_PK PRIMARY KEY,
   EVENT_NAME VARCHAR2(100) NOT NULL,
   EVENT_CONTENTS VARCHAR2(2000) NOT NULL,
   EVENT_DATE DATE DEFAULT SYSDATE   NOT NULL,
   EVENT_PROCESSING CHAR(1) DEFAULT 'Y' CHECK(EVENT_PROCESSING IN('Y','N'))   NOT NULL,
   EVENT_STATUS CHAR(1) DEFAULT 'Y' CHECK(EVENT_STATUS IN('Y','N'))   NOT NULL
);

CREATE TABLE TB_INQUIRY (
   INQ_NO NUMBER CONSTRAINT INQ_NO PRIMARY KEY,
   MEM_NO NUMBER REFERENCES TB_MEMBER ON DELETE CASCADE,
   INQ_NAME VARCHAR2(2000) NOT NULL,
   INQ_QUESTION VARCHAR2(2000) NOT NULL,
   INQ_DATE DATE DEFAULT SYSDATE   NOT NULL,
   INQ_ANSWER VARCHAR2(2000) NULL,
   INQ_PROCESSING CHAR(1) DEFAULT 'N' CHECK(INQ_PROCESSING IN('Y','N'))   NOT NULL,
   INQ_PRIVATE CHAR(1) DEFAULT 'Y' CHECK(INQ_PRIVATE IN('Y','N'))   NOT NULL,
   INQ_STATUS CHAR(1) DEFAULT 'Y'   CHECK(INQ_STATUS IN('Y','N')) NOT NULL
);

CREATE TABLE TB_REPORT (
   REP_NO NUMBER CONSTRAINT REP_NO_PK PRIMARY KEY,
   MEM_NO NUMBER REFERENCES TB_MEMBER ON DELETE CASCADE,
   REP_CONTENTS VARCHAR2(2000) NOT NULL,
   REP_DATE DATE DEFAULT SYSDATE NOT NULL,
   REP_CLSFC VARCHAR2(20) NOT NULL,
   REP_PROCESSING CHAR(1) DEFAULT 'N' CHECK(REP_PROCESSING IN('Y','N')) NOT NULL,
   REP_STATUS CHAR(1) DEFAULT 'Y'   NOT NULL
);

CREATE TABLE TB_EVENT_COMMENT (
   EVENT_COM_NO NUMBER CONSTRAINT EVENT_COM_NO_PK PRIMARY KEY,
   EVENT_NO NUMBER REFERENCES TB_EVENT ON DELETE CASCADE,
   MEM_NO NUMBER REFERENCES TB_MEMBER ON DELETE CASCADE,
   EVENT_COM_CONTENTS VARCHAR2(300) NOT NULL,
   EVENT_COM_DATE DATE DEFAULT SYSDATE NOT NULL,
   EVENT_COM_STATUS CHAR(1) DEFAULT 'Y' CHECK(EVENT_COM_STATUS IN('Y','N')) NOT NULL
);

CREATE TABLE TB_MAINIMG(
	MAINIMG_NO NUMBER CONSTRAINT MAINIMG_NO_PK PRIMARY KEY,
	MAINIMG_IMG VARCHAR2(300) NOT NULL
);

INSERT INTO TB_MEMBER
VALUES(0, 'admin', 'admin', 'admin', '관리자', '010-5344-1864', DEFAULT, NULL, DEFAULT);
INSERT INTO TB_MEMBER
VALUES(SEQ_MEM_NO.NEXTVAL, 'USER01', 'PASS01', 'NICK01', '김동현', '010-1111-1111', DEFAULT, 'MEM_IMG1', DEFAULT);
INSERT INTO TB_MEMBER
VALUES(SEQ_MEM_NO.NEXTVAL, 'USER02', 'PASS02', 'NICK02', '김연준', '010-2222-2222', DEFAULT, 'MEM_IMG2', DEFAULT);
INSERT INTO TB_MEMBER
VALUES(SEQ_MEM_NO.NEXTVAL, 'USER03', 'PASS03', 'NICK03', '김수민', '010-3333-3333', DEFAULT, 'MEM_IMG3', DEFAULT);
INSERT INTO TB_MEMBER
VALUES(SEQ_MEM_NO.NEXTVAL, 'USER04', 'PASS04', 'NICK04', '윤여진', '010-4444-4444', DEFAULT, 'MEM_IMG4', DEFAULT);
INSERT INTO TB_MEMBER
VALUES(SEQ_MEM_NO.NEXTVAL, 'USER05', 'PASS05', 'NICK05', '정민교', '010-5555-5555', DEFAULT, 'MEM_IMG5', DEFAULT);

-- 데이터 입력(TB_RECIPE 1번 게시글)
INSERT INTO TB_RECIPE
VALUES(SEQ_RECIPE_NO.NEXTVAL, '대파 닭꼬치', '#닭, #꼬치, #매콤', NULL, '중', 3, 30, DEFAULT, 1, 'C:\Users\PC\Desktop\KH\semi/logo.png', DEFAULT, DEFAULT);

-- 1번 게시글 재료
INSERT INTO TB_INGRE_CLASS
VALUES(SEQ_ING_C_NO.NEXTVAL, SEQ_RECIPE_NO.CURRVAL, DEFAULT);

INSERT INTO TB_INGREDIENT
VALUES(SEQ_INGRE_NO.NEXTVAL, SEQ_ING_C_NO.CURRVAL, '닭다리살', 500);

INSERT INTO TB_INGREDIENT
VALUES(SEQ_INGRE_NO.NEXTVAL, SEQ_ING_C_NO.CURRVAL, '대파', 1);

INSERT INTO TB_INGREDIENT
VALUES(SEQ_INGRE_NO.NEXTVAL, SEQ_ING_C_NO.CURRVAL, '기름', '약간');

INSERT INTO TB_INGREDIENT
VALUES(SEQ_INGRE_NO.NEXTVAL, SEQ_ING_C_NO.CURRVAL, '석쇠', 1);

INSERT INTO TB_INGRE_CLASS
VALUES(SEQ_ING_C_NO.NEXTVAL, SEQ_RECIPE_NO.CURRVAL, '데리야끼소스');

INSERT INTO TB_INGREDIENT
VALUES(SEQ_INGRE_NO.NEXTVAL, SEQ_ING_C_NO.CURRVAL, '간장', 4);

INSERT INTO TB_INGREDIENT
VALUES(SEQ_INGRE_NO.NEXTVAL, SEQ_ING_C_NO.CURRVAL, '청주', 4);

INSERT INTO TB_INGREDIENT
VALUES(SEQ_INGRE_NO.NEXTVAL, SEQ_ING_C_NO.CURRVAL, '미림', 4);

INSERT INTO TB_INGREDIENT
VALUES(SEQ_INGRE_NO.NEXTVAL, SEQ_ING_C_NO.CURRVAL, '설탕', 4);

INSERT INTO TB_INGRE_CLASS
VALUES(SEQ_ING_C_NO.NEXTVAL, SEQ_RECIPE_NO.CURRVAL, '닭다리살양념');

INSERT INTO TB_INGREDIENT
VALUES(SEQ_INGRE_NO.NEXTVAL, SEQ_ING_C_NO.CURRVAL, '간장', 2);

INSERT INTO TB_INGREDIENT
VALUES(SEQ_INGRE_NO.NEXTVAL, SEQ_ING_C_NO.CURRVAL, '생강가루', '약간');

INSERT INTO TB_INGREDIENT
VALUES(SEQ_INGRE_NO.NEXTVAL, SEQ_ING_C_NO.CURRVAL, '청주나 소주', 2);

INSERT INTO TB_INGREDIENT
VALUES(SEQ_INGRE_NO.NEXTVAL, SEQ_ING_C_NO.CURRVAL, '설탕', 1);

-- 1번 게시글 요리순서 & 요리순서이미지
INSERT INTO TB_COOKING_ORDER
VALUES(SEQ_CO_NO.NEXTVAL, SEQ_RECIPE_NO.CURRVAL, SEQ_CO_NO.CURRVAL, '닭다리살은 1개당 4~5등분으로 자르고 밑간 재료에 20분 정도 재워주세요.');

INSERT INTO TB_COOKING_ORDER_IMG
VALUES(SEQ_CO_NO.CURRVAL, 'https://recipe1.ezmember.co.kr/cache/recipe/2017/01/04/3ee2dea8fe7ef8c4bc73bd73c0bf22821.jpg');

INSERT INTO TB_COOKING_ORDER
VALUES(SEQ_CO_NO.NEXTVAL, SEQ_RECIPE_NO.CURRVAL, SEQ_CO_NO.CURRVAL, '대파는 3센치 길이로 썰어주세요. 볼에 양념 재료를 넣고 섞어주세요.');

INSERT INTO TB_COOKING_ORDER_IMG
VALUES(SEQ_CO_NO.CURRVAL, 'https://recipe1.ezmember.co.kr/cache/recipe/2017/01/04/ecf1eec4a22cddfa5431781e68f160d51.jpg');

INSERT INTO TB_COOKING_ORDER
VALUES(SEQ_CO_NO.NEXTVAL, SEQ_RECIPE_NO.CURRVAL, SEQ_CO_NO.CURRVAL, '닭고기와 대파를 꼬치에 번갈아 가며 끼운 후 양념을 발라주세요.');

INSERT INTO TB_COOKING_ORDER_IMG
VALUES(SEQ_CO_NO.CURRVAL, 'https://recipe1.ezmember.co.kr/cache/recipe/2017/01/04/3c4287eb7ec9dd421dc4833ed816b60f1.jpg');

INSERT INTO TB_COOKING_ORDER
VALUES(SEQ_CO_NO.NEXTVAL, SEQ_RECIPE_NO.CURRVAL, SEQ_CO_NO.CURRVAL, '구이 전용 팬에 닭 꼬치를 올린 후 4단에 넣고 광파오븐 자동 요리 <구이>에서 <닭 꼬치>를 선택한 후 500g을 선택해 구워주세요. 도중에 멜로디가 울리면 한번 뒤집어 주세요.');

INSERT INTO TB_COOKING_ORDER_IMG
VALUES(SEQ_CO_NO.CURRVAL, 'https://recipe1.ezmember.co.kr/cache/recipe/2017/01/04/2e6da04b035e5534c5921fdb5a182e9d1.jpg');

INSERT INTO TB_COOKING_ORDER
VALUES(SEQ_CO_NO.NEXTVAL, SEQ_RECIPE_NO.CURRVAL, SEQ_CO_NO.CURRVAL, '완성된 닭 꼬치에 송송 썬 쪽파를 뿌려  맛있게 즐겨주세요.');

INSERT INTO TB_COOKING_ORDER_IMG
VALUES(SEQ_CO_NO.CURRVAL, 'https://recipe1.ezmember.co.kr/cache/recipe/2017/01/04/55b38017928250fada34014dec0239ae1.jpg');

-- 1번 게시글 댓글
INSERT INTO TB_COMMENT
VALUES(SEQ_COM_NO.NEXTVAL, SEQ_RECIPE_NO.CURRVAL, '맛있어보이네요! 주말에 해보겠습니다', 2, SYSDATE, DEFAULT);

-- 1번 게시글 후기
INSERT INTO TB_REVIEW
VALUES(SEQ_REV_NO.NEXTVAL, SEQ_RECIPE_NO.CURRVAL, '쉽게 따라할 수 있고 아이들이 좋아하네요! 찜할게요!', 'https://recipe1.ezmember.co.kr/cache/review/2017/07/13/926a2d5f7363b849adf5b564793aae22.jpg', 3, SYSDATE, DEFAULT);

-- 데이터 입력(TB_RECIPE 2번 게시글)
INSERT INTO TB_RECIPE
VALUES(SEQ_RECIPE_NO.NEXTVAL, '비엔나 만두 강정', '#간단, #만두', 'https://youtu.be/y4aImV_6dQc', '하', 2, 15, DEFAULT, 2, 'C:\Users\PC\Desktop\KH\semi/mainpic.png', DEFAULT, DEFAULT);

-- 2번 게시글 재료
INSERT INTO TB_INGRE_CLASS
VALUES(SEQ_ING_C_NO.NEXTVAL, SEQ_RECIPE_NO.CURRVAL, '만두(교자만두/물만두)');

INSERT INTO TB_INGREDIENT
VALUES(SEQ_INGRE_NO.NEXTVAL, SEQ_ING_C_NO.CURRVAL, '비엔나소세지', 1);

INSERT INTO TB_INGREDIENT
VALUES(SEQ_INGRE_NO.NEXTVAL, SEQ_ING_C_NO.CURRVAL, '물', 1);

INSERT INTO TB_INGREDIENT
VALUES(SEQ_INGRE_NO.NEXTVAL, SEQ_ING_C_NO.CURRVAL, '간장', 1);

INSERT INTO TB_INGREDIENT
VALUES(SEQ_INGRE_NO.NEXTVAL, SEQ_ING_C_NO.CURRVAL, '고추장', 2);

INSERT INTO TB_INGREDIENT
VALUES(SEQ_INGRE_NO.NEXTVAL, SEQ_ING_C_NO.CURRVAL, '케찹', 2);

INSERT INTO TB_INGREDIENT
VALUES(SEQ_INGRE_NO.NEXTVAL, SEQ_ING_C_NO.CURRVAL, '올리고당', 1.5);

INSERT INTO TB_INGREDIENT
VALUES(SEQ_INGRE_NO.NEXTVAL, SEQ_ING_C_NO.CURRVAL, '다진마늘', 1);

INSERT INTO TB_INGREDIENT
VALUES(SEQ_INGRE_NO.NEXTVAL, SEQ_ING_C_NO.CURRVAL, '참기름', '약간');

INSERT INTO TB_INGREDIENT
VALUES(SEQ_INGRE_NO.NEXTVAL, SEQ_ING_C_NO.CURRVAL, '깨', '약간');

-- 2번 게시글 요리순서 & 요리순서이미지
INSERT INTO TB_COOKING_ORDER
VALUES(SEQ_CO_NO.NEXTVAL, SEQ_RECIPE_NO.CURRVAL, SEQ_CO_NO.CURRVAL, '만두는 기름을 두룬 팬에 노릇하게 구워줍니다.   ');

INSERT INTO TB_COOKING_ORDER_IMG
VALUES(SEQ_CO_NO.CURRVAL, 'https://recipe1.ezmember.co.kr/cache/recipe/2017/09/28/8fc533297f2fc246cbbf5f2fd1c8dfc21.jpg');

INSERT INTO TB_COOKING_ORDER
VALUES(SEQ_CO_NO.NEXTVAL, SEQ_RECIPE_NO.CURRVAL, SEQ_CO_NO.CURRVAL, '비엔나 소세지에 원하는 모양대로 칼집을 내고 팬에 볶아줍니다. 양파가 있다면 같이 볶아줘도 좋아요:)');

INSERT INTO TB_COOKING_ORDER_IMG
VALUES(SEQ_CO_NO.CURRVAL, 'https://recipe1.ezmember.co.kr/cache/recipe/2017/09/28/199b0d79568471660afcb5a4ac07b3171.jpg');

INSERT INTO TB_COOKING_ORDER
VALUES(SEQ_CO_NO.NEXTVAL, SEQ_RECIPE_NO.CURRVAL, SEQ_CO_NO.CURRVAL, '비엔나가 어느정도 구워지면 만두를 같이 넣어줍니다.   ');

INSERT INTO TB_COOKING_ORDER_IMG
VALUES(SEQ_CO_NO.CURRVAL, 'https://recipe1.ezmember.co.kr/cache/recipe/2017/09/28/04feae556dcd5899ef67ffb89e051fb51.jpg');

INSERT INTO TB_COOKING_ORDER
VALUES(SEQ_CO_NO.NEXTVAL, SEQ_RECIPE_NO.CURRVAL, SEQ_CO_NO.CURRVAL, '양념장을 넣고 양념이 고루 베이도록 잘 섞어줍니다');

INSERT INTO TB_COOKING_ORDER_IMG
VALUES(SEQ_CO_NO.CURRVAL, 'https://recipe1.ezmember.co.kr/cache/recipe/2017/09/28/05e4e16467b13cc29ffa7c1d07e8cc911.jpg');

INSERT INTO TB_COOKING_ORDER
VALUES(SEQ_CO_NO.NEXTVAL, SEQ_RECIPE_NO.CURRVAL, SEQ_CO_NO.CURRVAL, '양념이 어느정도 베이면 위에 통깨를 뿌려 마무리합니다.');

INSERT INTO TB_COOKING_ORDER_IMG
VALUES(SEQ_CO_NO.CURRVAL, 'https://recipe1.ezmember.co.kr/cache/recipe/2017/09/28/61da0ef87e2a754dc739eb177c3395341.jpg');

INSERT INTO TB_COOKING_ORDER
VALUES(SEQ_CO_NO.NEXTVAL, SEQ_RECIPE_NO.CURRVAL, SEQ_CO_NO.CURRVAL, '간식이나 술안주, 밑반찬으로 먹기 좋은 비엔나만두강정 완성!');

INSERT INTO TB_COOKING_ORDER_IMG
VALUES(SEQ_CO_NO.CURRVAL, 'https://recipe1.ezmember.co.kr/cache/recipe/2017/09/28/83c2df92a39da5d4ab9e238b8722b72a1.jpg');

-- 2번 게시글 댓글
INSERT INTO TB_COMMENT
VALUES(SEQ_COM_NO.NEXTVAL, SEQ_RECIPE_NO.CURRVAL, '정신없이 하다가 사진을 안찍었네요! 다음에도 또 해볼게요', 3, SYSDATE, DEFAULT);

-- 2번 게시글 후기
INSERT INTO TB_REVIEW
VALUES(SEQ_REV_NO.NEXTVAL, SEQ_RECIPE_NO.CURRVAL, '아침에 간단하게 만들기 좋은 반찬요리인것 같아요!', 'https://recipe1.ezmember.co.kr/cache/review/2020/09/09/2f565264dcc287547f9e95ecc009e9871.jpg', 4, SYSDATE, DEFAULT);

-- 데이터 입력(TB_RECIPE 3번 게시글)
INSERT INTO TB_RECIPE
VALUES(SEQ_RECIPE_NO.NEXTVAL, '추운 날 속 뜨끈 한 1000원 김치 콩나물 국', '#얼큰, #칼칼, #겨울', NULL, '중', 2, 10, DEFAULT, 3, 'https://recipe1.ezmember.co.kr/cache/recipe/2023/01/15/780d9d434e922fb4993e4984e6fb52561.jpg', DEFAULT, DEFAULT);

-- 3번 게시글 재료
INSERT INTO TB_INGRE_CLASS
VALUES (SEQ_ING_C_NO.NEXTVAL, SEQ_RECIPE_NO.CURRVAL, DEFAULT);

INSERT INTO TB_INGREDIENT
VALUES(SEQ_INGRE_NO.NEXTVAL, SEQ_ING_C_NO.CURRVAL, '콩나물', 1);

INSERT INTO TB_INGREDIENT
VALUES(SEQ_INGRE_NO.NEXTVAL, SEQ_ING_C_NO.CURRVAL, '신김치', 1);

INSERT INTO TB_INGREDIENT
VALUES(SEQ_INGRE_NO.NEXTVAL, SEQ_ING_C_NO.CURRVAL,  '파', 1);

INSERT INTO TB_INGREDIENT
VALUES(SEQ_INGRE_NO.NEXTVAL, SEQ_ING_C_NO.CURRVAL, '청양고추', 2);

INSERT INTO TB_INGREDIENT
VALUES(SEQ_INGRE_NO.NEXTVAL, SEQ_ING_C_NO.CURRVAL, '물', 1);

INSERT INTO TB_INGREDIENT
VALUES(SEQ_INGRE_NO.NEXTVAL, SEQ_ING_C_NO.CURRVAL, '멸치다시마육수팩', 1);

INSERT INTO TB_INGREDIENT
VALUES(SEQ_INGRE_NO.NEXTVAL, SEQ_ING_C_NO.CURRVAL, '다진마늘', 1);

INSERT INTO TB_INGREDIENT
VALUES(SEQ_INGRE_NO.NEXTVAL, SEQ_ING_C_NO.CURRVAL, '고춧가루', 1);

INSERT INTO TB_INGREDIENT
VALUES(SEQ_INGRE_NO.NEXTVAL, SEQ_ING_C_NO.CURRVAL, '국간장', 1);

INSERT INTO TB_INGREDIENT
VALUES(SEQ_INGRE_NO.NEXTVAL, SEQ_ING_C_NO.CURRVAL, '참치액젓', 1);

INSERT INTO TB_INGREDIENT
VALUES(SEQ_INGRE_NO.NEXTVAL, SEQ_ING_C_NO.CURRVAL, '김치국물', 1);

INSERT INTO TB_INGREDIENT
VALUES(SEQ_INGRE_NO.NEXTVAL, SEQ_ING_C_NO.CURRVAL, '소금', '적당량');

INSERT INTO TB_INGREDIENT
VALUES(SEQ_INGRE_NO.NEXTVAL, SEQ_ING_C_NO.CURRVAL, '후추', '약간');

-- 3번 게시글 요리순서 & 요리순서이미지
INSERT INTO TB_COOKING_ORDER
VALUES(SEQ_CO_NO.NEXTVAL, SEQ_RECIPE_NO.CURRVAL, SEQ_CO_NO.CURRVAL, '콩나물은 잘 씻어서 채에 받쳐주세요');

INSERT INTO TB_COOKING_ORDER_IMG
VALUES(SEQ_CO_NO.CURRVAL, 'https://recipe1.ezmember.co.kr/cache/recipe/2023/01/31/cfa6ad0536338d0a8a0ab964b125ac611.jpg');

INSERT INTO TB_COOKING_ORDER
VALUES(SEQ_CO_NO.NEXTVAL, SEQ_RECIPE_NO.CURRVAL, SEQ_CO_NO.CURRVAL, '물 1리터를 넣고 다시팩을 넣어 육수를 내주세요');

INSERT INTO TB_COOKING_ORDER_IMG
VALUES(SEQ_CO_NO.CURRVAL, 'https://recipe1.ezmember.co.kr/cache/recipe/2023/01/31/2917c38e66c28258c81e0dea59c2651c1.jpg');

INSERT INTO TB_COOKING_ORDER
VALUES(SEQ_CO_NO.NEXTVAL, SEQ_RECIPE_NO.CURRVAL, SEQ_CO_NO.CURRVAL, '그 사이 김치를 송송 썰어주세요');

INSERT INTO TB_COOKING_ORDER_IMG
VALUES(SEQ_CO_NO.CURRVAL, 'https://recipe1.ezmember.co.kr/cache/recipe/2023/01/31/e01428ff48ccaa00b1e29e34413c0f961.jpg');

INSERT INTO TB_COOKING_ORDER
VALUES(SEQ_CO_NO.NEXTVAL, SEQ_RECIPE_NO.CURRVAL, SEQ_CO_NO.CURRVAL, '물이 끓어오르면 다시팩을 건져 버려주세요');

INSERT INTO TB_COOKING_ORDER_IMG
VALUES(SEQ_CO_NO.CURRVAL, 'https://recipe1.ezmember.co.kr/cache/recipe/2023/01/31/2cdd812d69e1f4a4d109de023b41b44f1.jpg');

INSERT INTO TB_COOKING_ORDER
VALUES(SEQ_CO_NO.NEXTVAL, SEQ_RECIPE_NO.CURRVAL, SEQ_CO_NO.CURRVAL, '송송썬 김치와 김치국물 1국자를 넣어주세요');

INSERT INTO TB_COOKING_ORDER_IMG
VALUES(SEQ_CO_NO.CURRVAL, 'https://recipe1.ezmember.co.kr/cache/recipe/2023/01/31/bb393a55546a7767d64344a99e5aeef61.jpg');

INSERT INTO TB_COOKING_ORDER
VALUES(SEQ_CO_NO.NEXTVAL, SEQ_RECIPE_NO.CURRVAL, SEQ_CO_NO.CURRVAL, '다진마늘도 넣어주세요');

INSERT INTO TB_COOKING_ORDER_IMG
VALUES(SEQ_CO_NO.CURRVAL, 'https://recipe1.ezmember.co.kr/cache/recipe/2023/01/31/09ddb86fa43da9629b2251b0344950fc1.jpg');

INSERT INTO TB_COOKING_ORDER
VALUES(SEQ_CO_NO.NEXTVAL, SEQ_RECIPE_NO.CURRVAL, SEQ_CO_NO.CURRVAL, '참치액 1큰술 + 국간장 1큰술+ 고추가루 1큰술을 넣어 끓여주세요');

INSERT INTO TB_COOKING_ORDER_IMG
VALUES(SEQ_CO_NO.CURRVAL, 'https://recipe1.ezmember.co.kr/cache/recipe/2023/01/31/f3fa9fe524839f00a910d154d838e7531.jpg');

INSERT INTO TB_COOKING_ORDER
VALUES(SEQ_CO_NO.NEXTVAL, SEQ_RECIPE_NO.CURRVAL, SEQ_CO_NO.CURRVAL, '거품을 건져 버려주세요');

INSERT INTO TB_COOKING_ORDER_IMG
VALUES(SEQ_CO_NO.CURRVAL, 'https://recipe1.ezmember.co.kr/cache/recipe/2023/01/31/c36d04e66a8e46dc3d26c6927dbd9a7c1.jpg');

INSERT INTO TB_COOKING_ORDER
VALUES(SEQ_CO_NO.NEXTVAL, SEQ_RECIPE_NO.CURRVAL, SEQ_CO_NO.CURRVAL, '끓어오르면 씻어 놓은 콩나물을 넣어주세요 막 끓어오르면 간을 봐 주시고 싱거우면 소금을 넣어 입맛에 맞게 간을 해주세요');

INSERT INTO TB_COOKING_ORDER_IMG
VALUES(SEQ_CO_NO.CURRVAL, 'https://recipe1.ezmember.co.kr/cache/recipe/2023/01/31/a0d0ec36fb5b9c8fb93d9026efc0d0201.jpg');

INSERT INTO TB_COOKING_ORDER
VALUES(SEQ_CO_NO.NEXTVAL, SEQ_RECIPE_NO.CURRVAL, SEQ_CO_NO.CURRVAL, '고추는 먹을 때 불편해서 두 동강이 내서 국물만 내주고 건져주세요');

INSERT INTO TB_COOKING_ORDER_IMG
VALUES(SEQ_CO_NO.CURRVAL, 'https://recipe1.ezmember.co.kr/cache/recipe/2023/01/31/39e4f894500af7e01cae963db7967acc1.jpg');

-- 3번 게시글 댓글
INSERT INTO TB_COMMENT
VALUES(SEQ_COM_NO.NEXTVAL, SEQ_RECIPE_NO.CURRVAL, '해장으로 완벽하네요..', 4, SYSDATE, DEFAULT);

-- 3번 게시글 후기
INSERT INTO TB_REVIEW
VALUES(SEQ_REV_NO.NEXTVAL, SEQ_RECIPE_NO.CURRVAL, '간단하고 종종 해먹기 좋은것같아요^^', 'https://recipe1.ezmember.co.kr/cache/recipe/2017/08/30/2ac5cab916566dbe2a5a673a372423111_m.jpg', 1, SYSDATE, DEFAULT);

-- 데이터 입력(TB_RECIPE 4번 게시글)
INSERT INTO TB_RECIPE
VALUES(SEQ_RECIPE_NO.NEXTVAL, '오랜만에 집에 온 아들을 위한 쇠고기스테이크', '#소고기, #스테이크', NULL, '하', 2, 15, DEFAULT, 4, 'https://recipe1.ezmember.co.kr/cache/recipe/2023/02/03/ed10f757c71a440ab502066d5e12784b1.jpg', DEFAULT, DEFAULT);

-- 4번 게시글 재료
INSERT INTO TB_INGRE_CLASS
VALUES(SEQ_ING_C_NO.NEXTVAL, SEQ_RECIPE_NO.CURRVAL, DEFAULT);

INSERT INTO TB_INGREDIENT
VALUES(SEQ_INGRE_NO.NEXTVAL, SEQ_ING_C_NO.CURRVAL, '쇠고기', 400);

INSERT INTO TB_INGREDIENT
VALUES(SEQ_INGRE_NO.NEXTVAL, SEQ_ING_C_NO.CURRVAL, '파프리카', '1/2');

INSERT INTO TB_INGREDIENT
VALUES(SEQ_INGRE_NO.NEXTVAL, SEQ_ING_C_NO.CURRVAL, '딸기', 3);

INSERT INTO TB_INGREDIENT
VALUES(SEQ_INGRE_NO.NEXTVAL, SEQ_ING_C_NO.CURRVAL, '미나리', 1);

INSERT INTO TB_INGREDIENT
VALUES(SEQ_INGRE_NO.NEXTVAL, SEQ_ING_C_NO.CURRVAL, '후추', 1);

INSERT INTO TB_INGREDIENT
VALUES(SEQ_INGRE_NO.NEXTVAL, SEQ_ING_C_NO.CURRVAL, '새송이버섯', 1);

INSERT INTO TB_INGREDIENT
VALUES(SEQ_INGRE_NO.NEXTVAL, SEQ_ING_C_NO.CURRVAL, '양파', '1/2');

INSERT INTO TB_INGREDIENT
VALUES(SEQ_INGRE_NO.NEXTVAL, SEQ_ING_C_NO.CURRVAL, '허브솔트', 1);

INSERT INTO TB_INGREDIENT
VALUES(SEQ_INGRE_NO.NEXTVAL, SEQ_ING_C_NO.CURRVAL, '소금', 1);

INSERT INTO TB_INGREDIENT
VALUES(SEQ_INGRE_NO.NEXTVAL, SEQ_ING_C_NO.CURRVAL, '올리브유', 2);

-- 4번 게시글 요리순서 & 요리순서이미지
INSERT INTO TB_COOKING_ORDER
VALUES(SEQ_CO_NO.NEXTVAL, SEQ_RECIPE_NO.CURRVAL, SEQ_CO_NO.CURRVAL, '쇠고기는 칼끝으로 힘줄을 끊어주고 새송이버섯, 파프리카, 양파는 먹기 좋은 크기로 썰어둔다.');

INSERT INTO TB_COOKING_ORDER_IMG
VALUES(SEQ_CO_NO.CURRVAL, 'https://recipe1.ezmember.co.kr/cache/recipe/2023/02/03/d9173b2113b4528c037d0d2fe5a044901.jpg');

INSERT INTO TB_COOKING_ORDER
VALUES(SEQ_CO_NO.NEXTVAL, SEQ_RECIPE_NO.CURRVAL, SEQ_CO_NO.CURRVAL, '식용유를 두르고 썰어둔 채소를 넣고 허브솔트로 간을 한 후 노릇하게 구워준다.');

INSERT INTO TB_COOKING_ORDER_IMG
VALUES(SEQ_CO_NO.CURRVAL, 'https://recipe1.ezmember.co.kr/cache/recipe/2023/02/03/45af706b00b803598c45d77c2b0bc3411.jpg');

INSERT INTO TB_COOKING_ORDER
VALUES(SEQ_CO_NO.NEXTVAL, SEQ_RECIPE_NO.CURRVAL, SEQ_CO_NO.CURRVAL, '고기에 올리브유, 허브솔트를 뿌려둔다.   ');

INSERT INTO TB_COOKING_ORDER_IMG
VALUES(SEQ_CO_NO.CURRVAL, 'https://recipe1.ezmember.co.kr/cache/recipe/2023/02/03/a5c5b37a1bb79f459fe7da2ad527f0371.jpg');

INSERT INTO TB_COOKING_ORDER
VALUES(SEQ_CO_NO.NEXTVAL, SEQ_RECIPE_NO.CURRVAL, SEQ_CO_NO.CURRVAL, '프라이팬에 올려 구워준다.');

INSERT INTO TB_COOKING_ORDER_IMG
VALUES(SEQ_CO_NO.CURRVAL, 'https://recipe1.ezmember.co.kr/cache/recipe/2023/02/03/17fd748c1956b89f43805af4729431ec1.jpg');

INSERT INTO TB_COOKING_ORDER
VALUES(SEQ_CO_NO.NEXTVAL, SEQ_RECIPE_NO.CURRVAL, SEQ_CO_NO.CURRVAL, '구워둔 채소와 스테이크를 담아준다.');

INSERT INTO TB_COOKING_ORDER_IMG
VALUES(SEQ_CO_NO.CURRVAL, 'https://recipe1.ezmember.co.kr/cache/recipe/2023/02/03/0fe662825ef57c4378b325672e9ab8c41.jpg');

INSERT INTO TB_COOKING_ORDER
VALUES(SEQ_CO_NO.NEXTVAL, SEQ_RECIPE_NO.CURRVAL, SEQ_CO_NO.CURRVAL, '딸기, 미나리를 올려 마무리한다.');

INSERT INTO TB_COOKING_ORDER_IMG
VALUES(SEQ_CO_NO.CURRVAL, 'https://recipe1.ezmember.co.kr/cache/recipe/2023/02/03/b8761cd81822f12a618ef3ff1cfac19e1.jpg');

-- 4번 게시글 댓글
INSERT INTO TB_COMMENT
VALUES(SEQ_COM_NO.NEXTVAL, SEQ_RECIPE_NO.CURRVAL, '맛있네요!!!!', 5, SYSDATE, DEFAULT);

-- 4번 게시글 후기
INSERT INTO TB_REVIEW
VALUES(SEQ_REV_NO.NEXTVAL, SEQ_RECIPE_NO.CURRVAL, '반찬으로도 좋고 안주로도 좋네요!', 'https://recipe1.ezmember.co.kr/cache/recipe/2018/10/24/fd75db19796b172643d3a6d9136700801_m.jpg', 2, SYSDATE, DEFAULT);

-- 데이터 입력(TB_RECIPE 5번 게시글)
INSERT INTO TB_RECIPE
VALUES(SEQ_RECIPE_NO.NEXTVAL, '【10분만에 고급진 요리】파프리카소고기말이', '#초간단, #소고기', NULL, '상', 2, 30, DEFAULT, 5, 'https://recipe1.ezmember.co.kr/cache/recipe/2017/04/24/9765639935fc28e17b598a9c4f93ca1a1.jpg', DEFAULT, DEFAULT);

-- 5번 게시글 재료 & 양념 & 양념재료
INSERT INTO TB_INGRE_CLASS
VALUES(SEQ_ING_C_NO.NEXTVAL, SEQ_RECIPE_NO.CURRVAL, DEFAULT);

INSERT INTO TB_INGREDIENT
VALUES(SEQ_INGRE_NO.NEXTVAL, SEQ_ING_C_NO.CURRVAL, '얇게 썬 소고기', 6);

INSERT INTO TB_INGREDIENT
VALUES(SEQ_INGRE_NO.NEXTVAL, SEQ_ING_C_NO.CURRVAL, '깻잎', 6);

INSERT INTO TB_INGREDIENT
VALUES(SEQ_INGRE_NO.NEXTVAL, SEQ_ING_C_NO.CURRVAL, '파프리카(색깔별로)', '1/3');

INSERT INTO TB_INGREDIENT
VALUES(SEQ_INGRE_NO.NEXTVAL, SEQ_ING_C_NO.CURRVAL, '간장', 1);

INSERT INTO TB_INGREDIENT
VALUES(SEQ_INGRE_NO.NEXTVAL, SEQ_ING_C_NO.CURRVAL, '물', 1);

INSERT INTO TB_INGREDIENT
VALUES(SEQ_INGRE_NO.NEXTVAL, SEQ_ING_C_NO.CURRVAL, '식초', 1);

INSERT INTO TB_INGREDIENT
VALUES(SEQ_INGRE_NO.NEXTVAL, SEQ_ING_C_NO.CURRVAL, '설탕', 1);

INSERT INTO TB_INGREDIENT
VALUES(SEQ_INGRE_NO.NEXTVAL, SEQ_ING_C_NO.CURRVAL, '소금', '6번톡톡');

INSERT INTO TB_INGREDIENT
VALUES(SEQ_INGRE_NO.NEXTVAL, SEQ_ING_C_NO.CURRVAL, '후추', '6번톡톡');

-- 5번 게시글 요리순서 & 요리순서이미지
INSERT INTO TB_COOKING_ORDER
VALUES(SEQ_CO_NO.NEXTVAL, SEQ_RECIPE_NO.CURRVAL, SEQ_CO_NO.CURRVAL, '(6개 기준입니다)소고기는 얇게썬 불고기용으로 6장 준비 해주시구요~고기가 녹으면 키친타올로 살짝살짝 핏물을 닦아 주셔요~고기 하나당 후추,소금 한번씩만 톡 해서 살짝만 밑간을 해주세요');

INSERT INTO TB_COOKING_ORDER_IMG
VALUES(SEQ_CO_NO.CURRVAL, 'https://recipe1.ezmember.co.kr/cache/recipe/2017/04/24/cb8d0d829b947d0daa7b192cdb636aa01.jpg');

INSERT INTO TB_COOKING_ORDER
VALUES(SEQ_CO_NO.NEXTVAL, SEQ_RECIPE_NO.CURRVAL, SEQ_CO_NO.CURRVAL, '파프리카 색깔별로 1/3쪽씩 채썰어 주시구요 깻잎6장 씻어서 준비해주세요');

INSERT INTO TB_COOKING_ORDER_IMG
VALUES(SEQ_CO_NO.CURRVAL, 'https://recipe1.ezmember.co.kr/cache/recipe/2017/04/24/f090c38a1365f29c57f0f7787034ac0b1.jpg');

INSERT INTO TB_COOKING_ORDER
VALUES(SEQ_CO_NO.NEXTVAL, SEQ_RECIPE_NO.CURRVAL, SEQ_CO_NO.CURRVAL, '해동된 소고기는 밑에 깔고 깻잎올려 파프리카를 색깔별로 올려');

INSERT INTO TB_COOKING_ORDER_IMG
VALUES(SEQ_CO_NO.CURRVAL, 'https://recipe1.ezmember.co.kr/cache/recipe/2017/04/24/f9fe79fd49ba77487f8093ba7ba310271.jpg');

INSERT INTO TB_COOKING_ORDER
VALUES(SEQ_CO_NO.NEXTVAL, SEQ_RECIPE_NO.CURRVAL, SEQ_CO_NO.CURRVAL, '깻잎부터 돌돌말고 소고기를 말아 주세요~');

INSERT INTO TB_COOKING_ORDER_IMG
VALUES(SEQ_CO_NO.CURRVAL, 'https://recipe1.ezmember.co.kr/cache/recipe/2017/04/24/c93329adb20c910d1254e9235a608abb1.jpg');

INSERT INTO TB_COOKING_ORDER
VALUES(SEQ_CO_NO.NEXTVAL, SEQ_RECIPE_NO.CURRVAL, SEQ_CO_NO.CURRVAL, '말아진 부분이 풀리지 않게 밑으로 가게끔 두시구요');

INSERT INTO TB_COOKING_ORDER_IMG
VALUES(SEQ_CO_NO.CURRVAL, 'https://recipe1.ezmember.co.kr/cache/recipe/2017/04/24/13ecd786640db87799fc57d74888235c1.jpg');

INSERT INTO TB_COOKING_ORDER
VALUES(SEQ_CO_NO.NEXTVAL, SEQ_RECIPE_NO.CURRVAL, SEQ_CO_NO.CURRVAL, '구우실때도 풀리지않게 말아진 끝부분 부터 구워 주세요~');

INSERT INTO TB_COOKING_ORDER_IMG
VALUES(SEQ_CO_NO.CURRVAL, 'https://recipe1.ezmember.co.kr/cache/recipe/2017/04/24/5791c838196f0bb18ef68a1ee0d68eb11.jpg');

INSERT INTO TB_COOKING_ORDER
VALUES(SEQ_CO_NO.NEXTVAL, SEQ_RECIPE_NO.CURRVAL, SEQ_CO_NO.CURRVAL, '식용유 살짝 둘러 약불로 고기만 익으면 끝이에요^~^');

INSERT INTO TB_COOKING_ORDER_IMG
VALUES(SEQ_CO_NO.CURRVAL, 'https://recipe1.ezmember.co.kr/cache/recipe/2017/04/24/7fdfbb0846d45c1a994fd67a3d73f2ed1.jpg');

INSERT INTO TB_COOKING_ORDER
VALUES(SEQ_CO_NO.NEXTVAL, SEQ_RECIPE_NO.CURRVAL, SEQ_CO_NO.CURRVAL, '구워진 소고기말이는 어슷썰어 주시면 완성입니다^~^');

INSERT INTO TB_COOKING_ORDER_IMG
VALUES(SEQ_CO_NO.CURRVAL, 'https://recipe1.ezmember.co.kr/cache/recipe/2017/04/24/564d7f329cb7a81f18cd3c7a5c49c1461.jpg');

-- 5번 게시글 댓글
INSERT INTO TB_COMMENT
VALUES(SEQ_COM_NO.NEXTVAL, SEQ_RECIPE_NO.CURRVAL, '따라하기 좋고 굳이네요~', 1, SYSDATE, DEFAULT);

-- 5번 게시글 후기
INSERT INTO TB_REVIEW
VALUES(SEQ_REV_NO.NEXTVAL, SEQ_RECIPE_NO.CURRVAL, '너무 맛있게 잘 해먹었어요 아들이 혼자 2인분을 뚝딱 ㅎㅎ 겨자소스에 양파채썰어서 하니까 느끼한 맛도 잡아주고 좋았어요 감사합니다  ', 'https://recipe1.ezmember.co.kr/cache/review/2021/01/30/ca7698f165a9f2bcf4d4f80c359894361.jpg', 3, SYSDATE, DEFAULT);


-- 데이터 입력(TB_CATEGORY_NATION-국가별)
INSERT INTO TB_CATEGORY_NATION(C_NAT_NO, C_NAT_NAME)
                        VALUES('N'|| SEQ_C_NAT_NO.NEXTVAL, '한국');
                               
INSERT INTO TB_CATEGORY_NATION(C_NAT_NO, C_NAT_NAME)
                        VALUES('N'|| SEQ_C_NAT_NO.NEXTVAL, '베트남');
                               
INSERT INTO TB_CATEGORY_NATION(C_NAT_NO, C_NAT_NAME)
                        VALUES('N'|| SEQ_C_NAT_NO.NEXTVAL, '중국');
                               
INSERT INTO TB_CATEGORY_NATION(C_NAT_NO, C_NAT_NAME)
                        VALUES('N'|| SEQ_C_NAT_NO.NEXTVAL, '이탈리아');
                               
INSERT INTO TB_CATEGORY_NATION(C_NAT_NO, C_NAT_NAME)
                        VALUES('N'|| SEQ_C_NAT_NO.NEXTVAL, '일본');
                               
                               
                               
-- 데이터 입력(TB_CATEGORY_STEP-조리방법)
INSERT INTO TB_CATEGORY_STEP(C_STEP_NO,C_STEP_NAME)
                        VALUES('S'||SEQ_C_STEP_NO.NEXTVAL, '구이');

INSERT INTO TB_CATEGORY_STEP(C_STEP_NO, C_STEP_NAME)
                        VALUES('S'||SEQ_C_STEP_NO.NEXTVAL, '찜');

INSERT INTO TB_CATEGORY_STEP(C_STEP_NO,C_STEP_NAME)
                        VALUES('S'||SEQ_C_STEP_NO.NEXTVAL, '볶음');

INSERT INTO TB_CATEGORY_STEP(C_STEP_NO,C_STEP_NAME)
                        VALUES('S'||SEQ_C_STEP_NO.NEXTVAL, '무침');

INSERT INTO TB_CATEGORY_STEP(C_STEP_NO,C_STEP_NAME)
                        VALUES('S'||SEQ_C_STEP_NO.NEXTVAL, '튀김');





-- 데이터 입력(TB_CATEGORY_TOOL-도구별)
INSERT INTO TB_CATEGORY_TOOL(C_TOOL_NO, C_TOOL_NAME)
                        VALUES('T'||SEQ_C_TOOL_NO.NEXTVAL, '냄비');

INSERT INTO TB_CATEGORY_TOOL(C_TOOL_NO,C_TOOL_NAME)
                        VALUES('T'||SEQ_C_TOOL_NO.NEXTVAL, '프라이팬');

INSERT INTO TB_CATEGORY_TOOL(C_TOOL_NO,C_TOOL_NAME)
                        VALUES('T'||SEQ_C_TOOL_NO.NEXTVAL, '전자레인지');

INSERT INTO TB_CATEGORY_TOOL(C_TOOL_NO,C_TOOL_NAME)
                        VALUES('T'||SEQ_C_TOOL_NO.NEXTVAL, '오븐');

INSERT INTO TB_CATEGORY_TOOL(C_TOOL_NO,C_TOOL_NAME)
                        VALUES('T'||SEQ_C_TOOL_NO.NEXTVAL, '에어프라이어');



-- 데이터 입력(TB_CATEGORY_KIND-종류별)
INSERT INTO TB_CATEGORY_KIND(C_KIND_NO,C_KIND_NAME)
                        VALUES('K'||SEQ_C_KIND_NO.NEXTVAL, '안주');

INSERT INTO TB_CATEGORY_KIND(C_KIND_NO,C_KIND_NAME)
                        VALUES('K'||SEQ_C_KIND_NO.NEXTVAL, '반찬');

INSERT INTO TB_CATEGORY_KIND(C_KIND_NO,C_KIND_NAME)
                        VALUES('K'||SEQ_C_KIND_NO.NEXTVAL, '국/탕');

INSERT INTO TB_CATEGORY_KIND(C_KIND_NO,C_KIND_NAME)
                        VALUES('K'||SEQ_C_KIND_NO.NEXTVAL, '샐러드');

INSERT INTO TB_CATEGORY_KIND(C_KIND_NO,C_KIND_NAME)
                        VALUES('K'||SEQ_C_KIND_NO.NEXTVAL, '디저트');

INSERT INTO TB_CATEGORY_KIND(C_KIND_NO,C_KIND_NAME)
                        VALUES('K'||SEQ_C_KIND_NO.NEXTVAL, '김치/젓갈');

INSERT INTO TB_CATEGORY_KIND(C_KIND_NO,C_KIND_NAME)
                        VALUES('K'||SEQ_C_KIND_NO.NEXTVAL, '차/음료/술');



-- 데이터 입력(TB_CATEGORY_THEME-테마별)
INSERT INTO TB_CATEGORY_THEME(C_THEME_NO,C_THEME_NAME)
                        VALUES('TM'||SEQ_C_THEME_NO.NEXTVAL, '건강식');
                               
INSERT INTO TB_CATEGORY_THEME(C_THEME_NO,C_THEME_NAME)
                        VALUES('TM'||SEQ_C_THEME_NO.NEXTVAL, '캠핑요리');
                               
INSERT INTO TB_CATEGORY_THEME(C_THEME_NO,C_THEME_NAME)
                        VALUES('TM'||SEQ_C_THEME_NO.NEXTVAL, '간단자취요리');
                               
INSERT INTO TB_CATEGORY_THEME(C_THEME_NO,C_THEME_NAME)
                        VALUES('TM'||SEQ_C_THEME_NO.NEXTVAL, '편의점꿀조합');
                               
INSERT INTO TB_CATEGORY_THEME(C_THEME_NO,C_THEME_NAME)
                        VALUES('TM'||SEQ_C_THEME_NO.NEXTVAL, '반려동물을 위한 요리');
                               
INSERT INTO TB_CATEGORY_THEME(C_THEME_NO,C_THEME_NAME)
                        VALUES('TM'||SEQ_C_THEME_NO.NEXTVAL, '파티요리');



-- 데이터 입력(TB_CATEGORY_INGREDIENT-재료별)
INSERT INTO TB_CATEGORY_INGREDIENT(C_INGRE_NO,C_INGRE_NAME)
                        VALUES('I'||SEQ_C_INGRE_NO.NEXTVAL, '소고기');

INSERT INTO TB_CATEGORY_INGREDIENT(C_INGRE_NO,C_INGRE_NAME)
                        VALUES('I'||SEQ_C_INGRE_NO.NEXTVAL, '돼지고기');

INSERT INTO TB_CATEGORY_INGREDIENT(C_INGRE_NO,C_INGRE_NAME)
                        VALUES('I'||SEQ_C_INGRE_NO.NEXTVAL, '소고기');
                               
INSERT INTO TB_CATEGORY_INGREDIENT(C_INGRE_NO,C_INGRE_NAME)
                        VALUES('I'||SEQ_C_INGRE_NO.NEXTVAL, '닭고기');

INSERT INTO TB_CATEGORY_INGREDIENT(C_INGRE_NO,C_INGRE_NAME)
                        VALUES('I'||SEQ_C_INGRE_NO.NEXTVAL, '해산물');

INSERT INTO TB_CATEGORY_INGREDIENT(C_INGRE_NO,C_INGRE_NAME)
                        VALUES('I'||SEQ_C_INGRE_NO.NEXTVAL, '채소');

INSERT INTO TB_MAINIMG VALUES(SEQ_MAINIMG_NO.NEXTVAL,'RESOURCES/IMG/MAINIMG1.JPG');
INSERT INTO TB_MAINIMG VALUES(SEQ_MAINIMG_NO.NEXTVAL,'RESOURCES/IMG/MAINIMG2.JPG');
INSERT INTO TB_MAINIMG VALUES(SEQ_MAINIMG_NO.NEXTVAL,'RESOURCES/IMG/MAINIMG3.JPG');
INSERT INTO TB_MAINIMG VALUES(SEQ_MAINIMG_NO.NEXTVAL,'RESOURCES/IMG/MAINIMG4.JPG');
INSERT INTO TB_MAINIMG VALUES(SEQ_MAINIMG_NO.NEXTVAL,'RESOURCES/IMG/MAINIMG5.JPG');
                         

-- 데이터 넣기(TB_CATEGORY)
INSERT INTO TB_CATEGORY VALUES(1, 'N1', 'S3', 'T1', 'K1', 'TM1', 'I1');
INSERT INTO TB_CATEGORY VALUES(2, 'N5', 'S2', 'T4', 'K3', 'TM2', 'I4');
INSERT INTO TB_CATEGORY VALUES(3, 'N2', 'S5', 'T5', 'K5', 'TM5', 'I3');
INSERT INTO TB_CATEGORY VALUES(4, 'N3', 'S4', 'T2', 'K4', 'TM3', 'I2');
INSERT INTO TB_CATEGORY VALUES(5, 'N4', 'S1', 'T3', 'K2', 'TM4', 'I5');

INSERT INTO TB_REPORT(
REP_NO,
MEM_NO,
REP_CONTENTS,
REP_DATE,
REP_CLSFC,
REP_PROCESSING,
REP_STATUS
)
VALUES (
SEQ_REP_NO.NEXTVAL,
1,
'의미없는 게시글 신고합니다 www.todaytable.com/~~~',
SYSDATE,
'게시글신고',
DEFAULT,
DEFAULT
);

INSERT INTO TB_REPORT(
REP_NO,
MEM_NO,
REP_CONTENTS,
REP_DATE,
REP_CLSFC,
REP_PROCESSING,
REP_STATUS
)
VALUES (
SEQ_REP_NO.NEXTVAL,
1,
'비매너 댓글 신고합니다 www.todaytable.com/~~~',
SYSDATE,
'댓글신고',
'Y',
DEFAULT
);

INSERT INTO TB_REPORT(
REP_NO,
MEM_NO,
REP_CONTENTS,
REP_DATE,
REP_CLSFC,
REP_PROCESSING,
REP_STATUS
)
VALUES (
SEQ_REP_NO.NEXTVAL,
3,
'욕설 댓글 신고합니다 www.todaytable.com/~~~',
SYSDATE,
'댓글신고',
DEFAULT,
DEFAULT
);

INSERT INTO TB_REPORT(
REP_NO,
MEM_NO,
REP_CONTENTS,
REP_DATE,
REP_CLSFC,
REP_PROCESSING,
REP_STATUS
)
VALUES (
SEQ_REP_NO.NEXTVAL,
4,
'비매너 게시글 신고합니다 www.todaytable.com/~~~',
SYSDATE,
'게시글신고',
DEFAULT,
DEFAULT
);

INSERT INTO TB_REPORT(
REP_NO,
MEM_NO,
REP_CONTENTS,
REP_DATE,
REP_CLSFC,
REP_PROCESSING,
REP_STATUS
)
VALUES (
SEQ_REP_NO.NEXTVAL,
1,
'게시글 신고접수 www.todaytable.com/~~~',
SYSDATE,
'게시글신고',
DEFAULT,
DEFAULT
);

-- TB_INQUIRY

INSERT INTO TB_INQUIRY(
INQ_NO,
MEM_NO,
INQ_NAME,
INQ_QUESTION,
INQ_DATE,
INQ_ANSWER,
INQ_PROCESSING,
INQ_PRIVATE,
INQ_STATUS
)
VALUES (
SEQ_INQ_NO.NEXTVAL,
1,
'레시피 조회 화면이 안나와요',
'원래 잘 됐는데 컴퓨터 바꾸고 나서 레시피 조회가 안되네요 답변부탁드립니다.',
SYSDATE,
'안녕하세요 오늘의 식탁입니다. 문의주신 내용 답변드리겠습니다.
조회가 안된다면 chrome 브라우저를 사용해보세요',
'Y',
DEFAULT,
DEFAULT
);

INSERT INTO TB_INQUIRY(
INQ_NO,
MEM_NO,
INQ_NAME,
INQ_QUESTION,
INQ_DATE,
INQ_ANSWER,
INQ_PROCESSING,
INQ_PRIVATE,
INQ_STATUS
)
VALUES (
SEQ_INQ_NO.NEXTVAL,
1,
'레시피를 보니까 배고파요',
'레시피를 보니까 배고프네요 ㅡㅡ;;',
SYSDATE,
NULL,
DEFAULT,
'Y',
DEFAULT
);

INSERT INTO TB_INQUIRY(
INQ_NO,
MEM_NO,
INQ_NAME,
INQ_QUESTION,
INQ_DATE,
INQ_ANSWER,
INQ_PROCESSING,
INQ_PRIVATE,
INQ_STATUS
)
VALUES (
SEQ_INQ_NO.NEXTVAL,
1,
'가지고 있는 레시피를 공유하려합니다.',
'제가 가지고 있는 비밀 레시피를 공유하려고합니다',
SYSDATE,
'안녕하세요 오늘의 식탁입니다.
레시피 작성을 이용해 공유해주세요',
'Y',
'Y',
DEFAULT
);

INSERT INTO TB_INQUIRY(
INQ_NO,
MEM_NO,
INQ_NAME,
INQ_QUESTION,
INQ_DATE,
INQ_ANSWER,
INQ_PROCESSING,
INQ_PRIVATE,
INQ_STATUS
)
VALUES (
SEQ_INQ_NO.NEXTVAL,
3,
'레시피 등록이 안돼요',
'레시피 등록이 안되네요 ;;;;',
SYSDATE,
'안녕하세요 오늘의 식탁입니다.
다시한번 시도해보세요',
'Y',
DEFAULT,
DEFAULT
);

INSERT INTO TB_INQUIRY(
INQ_NO,
MEM_NO,
INQ_NAME,
INQ_QUESTION,
INQ_DATE,
INQ_ANSWER,
INQ_PROCESSING,
INQ_PRIVATE,
INQ_STATUS
)
VALUES (
SEQ_INQ_NO.NEXTVAL,
5,
'분류별 레시피에서 404에러가 떠요',
'분류별 레시피에서 에러뜹니다 조치해주세여',
SYSDATE,
'안녕하세요 오늘의 식탁입니다.
현재 잘 됩니다.',
'Y',
DEFAULT,
DEFAULT
);

-- TB_NOTICE

INSERT INTO TB_NOTICE(
NOTICE_NO,
NOTICE_NAME,
NOTICE_CONTENTS,
NOTICE_DATE,
NOTICE_CLSFC,
NOTICE_STATUS)
VALUES (
SEQ_NOTICE_NO.NEXTVAL,
'2020년 부터 익스플로에서는 동영상이 나오지 않습니다',
'2020년 말부터 공식적으로 Adobe사의 플래시 플레이어 지원이 중단됨에 따라
플래시 플레이어를 통한 동영상 재생이 불가합니다
동영상이 나오는 브라우저로 업그레이드 하시기 바랍니다',
SYSDATE,
'일반',
DEFAULT
);

INSERT INTO TB_NOTICE(
NOTICE_NO,
NOTICE_NAME,
NOTICE_CONTENTS,
NOTICE_DATE,
NOTICE_CLSFC,
NOTICE_STATUS)
VALUES (
SEQ_NOTICE_NO.NEXTVAL,
'금일 8월 16일 업데이트가 있습니다',
'금일 서버 업데이트가 있어 서버접속과 기타 기능이 작동하지 않을수가 있습니니다 조속히 마치도록 하겠습니다
금일 작업은 8월 16일 저녁쯤에 끝날예정입니다
혹시 작동이 안되는 기능이 있으면 1:1 문의 게시판에 바로 부탁드립니다',
SYSDATE,
'긴급',
DEFAULT
);

INSERT INTO TB_NOTICE(
NOTICE_NO,
NOTICE_NAME,
NOTICE_CONTENTS,
NOTICE_DATE,
NOTICE_CLSFC,
NOTICE_STATUS)
VALUES (
SEQ_NOTICE_NO.NEXTVAL,
'서버 긴급 점검안내',
'서버점검으로가 있어 서버접속과 기타 기능이 작동하지 않을수가 있습니니다 조속히 마치도록 하겠습니다
감사합니다.',
SYSDATE,
'긴급',
DEFAULT
);

INSERT INTO TB_NOTICE(
NOTICE_NO,
NOTICE_NAME,
NOTICE_CONTENTS,
NOTICE_DATE,
NOTICE_CLSFC,
NOTICE_STATUS)
VALUES (
SEQ_NOTICE_NO.NEXTVAL,
'댓글 순서가 변경 되었습니다',
'기존의 댓글로 질문하시면 마지막 질문이 가장 끝으로 가서 보기가 불편하다는 의견이 있어
가장 최신 댓글 질문을 바로 상단에 위치하게 프로그램 하였습니다.',
SYSDATE,
'일반',
DEFAULT
);

INSERT INTO TB_NOTICE(
NOTICE_NO,
NOTICE_NAME,
NOTICE_CONTENTS,
NOTICE_DATE,
NOTICE_CLSFC,
NOTICE_STATUS)
VALUES (
SEQ_NOTICE_NO.NEXTVAL,
'오늘의식탁 개인정보 처리방침 변경 안내',
'안녕하세요.

오늘의식탁입니다.

오늘의식탁을 이용해주시는 회원 여러분들께 진심으로 감사드립니다.

오늘의식탁 내 개인정보 처리방침 변경에 관한 안내 말씀드립니다.

■ 변경사항

개인정보 처리방침 내 제 2조 2항 내용 추가

■ 적용일시

2022년 12월 6일

■ 변경 조항

제2조 2항 내용 변경

변경 전

２. 이용자는 회사의 서비스를 이용하기 위해서 회원 가입 시 개인정보를 입력해야 합니다.
가) 필수항목 : 아이디(ID), 비밀번호, 닉네임, 이메일주소, 성별, 생년월일
나) 선택항목 : 사진, 블로그 주소

변경 후

2. 이용자는 회사 서비스를 이용하기 위해 회원 가입 시 개인정보를 입력해야 합니다.

가) 일반 회원 가입
- 필수항목: 아이디, 비밀번호, 닉네임, 이메일, 성별, 생년월일
- 선택항목: 사진, 블로그 주소

나) SNS 가입
- 카카오 계정: 이메일, 닉네임, 프로필 사진
- 페이스북 계정: 이름, 이메일, 프로필사진
- 네이버 계정: 이메일, 별명, 프로필 사진,이름(선택), 성별(선택), 생일(선택), 연령대(선택)
- 구글 계정: 이름, 이메일, 프로필 사진, 언어
개정 약관의 내용에 대한 문의사항이 있으신 경우 고객센터로 접수해주시면 신속하고 친절하게 안내해드리겠습니다.
감사합니다.',
SYSDATE,
'일반',
DEFAULT
);

-- TB_EVENT

INSERT INTO TB_EVENT(
EVENT_NO,
EVENT_NAME,
EVENT_CONTENTS,
EVENT_DATE,
EVENT_PROCESSING,
EVENT_STATUS)
VALUES (
SEQ_EVENT_NO.NEXTVAL,
'우리집 만의 추석 음식 레시피를 알려주세요.',
'안녕하세요~오늘의 식탁입니다.
처서가 지나고 날씨가 시원해 지고 있어요.
곧 추석이 다가오는데요. 가족 친지들이 모두 모여 맛있는 음식도 먹고 즐기는 때인데요.~
추석 때 우리 집은 이 음식은 특별히 꼭 먹어요.~하는 것들이 있지나요?.

우리 집 만의 특별한 추석 음식 레시피를 알려주세요!
여러분들의 노하우가 담긴 특별한 레시피를 기대합니다.
상품이 가득한 오늘의식탁 공모전 주변 분들에게 입소문 많이 내주시길 부탁드려요 :)',
SYSDATE,
DEFAULT,
DEFAULT);

INSERT INTO TB_EVENT(
EVENT_NO,
EVENT_NAME,
EVENT_CONTENTS,
EVENT_DATE,
EVENT_PROCESSING,
EVENT_STATUS)
VALUES (
SEQ_EVENT_NO.NEXTVAL,
'2023 계묘년 당근 요리 레시피 이벤트',
'2023 계묘년 당근 요리 레시피를 알려주세요,
안녕하세요~오늘의 식탁입니다.
어느덧 2022년이 가고 2023년이 왔어요.~^^
올해는 토끼해라고 하네요. 올 한 해도 행복하고 건강한 2023년이 되셨으면 합니다.
귀여운 토끼가 좋아하고 건강에도 좋은 당근!!
당근으로 만든 특별한 레시피를 알려주세요.
여러분들의 노하우가 담긴 특별한 레시피를 기대합니다.
상품이 가득한 오늘의식탁 공모전 주변 분들에게 입소문 많이 내주시길 부탁드려요 :)
◎ 기간
- 응모 : 2022년 12월 31일~2023년 1월 31일 화요일 오후 5시
- 발표 : 2023년 2월 6일 월요일
◎ 선정기준
공모전 당첨자 총6명
- 주제에 맞는 레시피의 리뷰와 의견, 스크랩 수, 재료계량, 과정 설명, 과정 이미지가 잘 된 레시피와 아이디어가 돋보이는 레시피 대상으로 취합하여 선정 합니다.
※ 레시피 제목에 당근 또는 당근 연상 단어가 꼭 포함이 되어야 참여 인정.
※ 해당 월에 수상하신 경우, 해당 월에 진행하는 모든 공모전의 수상 대상에서 제외되며, 해당 월 다음 월에 진행하는 공모전부터 수상대상에 포함됩니다.
◎ 안내사항
- 공모전 요리 주제에 맞는 레시피를 등록해주세요.
- 전문레시피(직접등록/블로그 편집)만 응모 가능합니다
(※ 응모일 이전에 등록된 레시피는 제외)
- 주제와 맞지 않는 레시피는 수상 목록에서 제외될 수 있습니다.
- 공모전에 응모한 레시피는 재가공하여 오늘의식탁 영상 컨텐츠로 제작될 수 있습니다.
- 당첨자 발표는 따로 SMS를 전송하지 않습니다. 당첨자 발표일을 확인하시고 이벤트 페이지에서 확인하시기 바랍니다.
- 공모전 아이디어가 있으시면 [☞여기]를 통해 알려주세요.
- TV레시피는 수상대상에서 제외됩니다.',
SYSDATE,
'N',
DEFAULT);

INSERT INTO TB_EVENT(
EVENT_NO,
EVENT_NAME,
EVENT_CONTENTS,
EVENT_DATE,
EVENT_PROCESSING,
EVENT_STATUS)
VALUES (
SEQ_EVENT_NO.NEXTVAL,
'[인스타그램 이벤트] 수고했어요 수험생 응원 메세지 이벤트',
'수험생 여러분 모두 수고하셨습니다
오늘의식탁에서 수험생 여러분을 위한 수능이벤트를 준비했어요~
올 한해 수고한 친구, 가족, 그냥 좀 아는 사람을 포함한
주변의 수험생에게 응원메세지 남기고 함께 영화보러 갈 수 있는 기회!!
※ 참여방법
1) 인스타그램 계정(@10000recipe) 해당 게시물에 수능을 치룬 수험생 태그! (팔로우+게시물 하트 꾹~)
2) 올 한해 고생한 수험생을 힘나게 해줄 추천요리와 응원메세지를 댓글로 남긴다!
* 더 재치있고 더 감동적인 메세지를 남기면 당첨확률 up!
※ 해당 이벤트는 오늘의식탁 인스타그램 채널에서 진행되는 이벤트로
당첨자는 공식 계정을 통해 발표될 예정이니, 많은 참여 부탁드립니다 :)',
SYSDATE,
'N',
DEFAULT);

INSERT INTO TB_EVENT(
EVENT_NO,
EVENT_NAME,
EVENT_CONTENTS,
EVENT_DATE,
EVENT_PROCESSING,
EVENT_STATUS)
VALUES (
SEQ_EVENT_NO.NEXTVAL,
'편의점 꿀조합 레시피를 알려주세요.',
'"안녕하세요~오늘의 식탁입니다.
요즘 편의점에 가면 정말 다양한 제품들이 많아요.~
저는 비빔면에 소시지 조합을 좋아하는데요.
SNS나 유튜브 보면 정말 다양한 꿀 조합이 많더라구요.
나만의 편의점 꿀 조합 레시피를 알려주세요.

여러분들의 노하우가 담긴 특별한 꿀조합을 기대합니다.
상품이 가득한 오늘의식탁 공모전 주변 분들에게 입소문 많이 내주시길 부탁드려요 :)"',
SYSDATE,
DEFAULT,
DEFAULT);

INSERT INTO TB_EVENT(
EVENT_NO,
EVENT_NAME,
EVENT_CONTENTS,
EVENT_DATE,
EVENT_PROCESSING,
EVENT_STATUS)
VALUES (
SEQ_EVENT_NO.NEXTVAL,
'양파를 활용한 레시피를 알려주세요.',
'안녕하세요~오늘의 식탁입니다.
양파는 사계절 다 구하기 쉬운 재료에요. 지금은 햇양파가 많이 나오기도 하고요.
양파로 다양한 요리를 만들어주세요.
양파로 나만의 요리 레시피를 알려주세요.

여러분들의 노하우가 담긴 특별한 레시피를 기대합니다.
상품이 가득한 오늘의식탁 공모전 주변 분들에게 입 소문 많이 내주시길 부탁 드려요 :)',
SYSDATE,
'N',
DEFAULT);

-- TB_EVENT_COMMENT

INSERT INTO TB_EVENT_COMMENT(
EVENT_COM_NO,
EVENT_NO,
MEM_NO,
EVENT_COM_CONTENTS,
EVENT_COM_DATE,
EVENT_COM_STATUS)
VALUES (
SEQ_EVENT_COM_NO.NEXTVAL,
1,
2,
'이벤트 잘 봤습니다~~',
SYSDATE,
DEFAULT);

INSERT INTO TB_EVENT_COMMENT(
EVENT_COM_NO,
EVENT_NO,
MEM_NO,
EVENT_COM_CONTENTS,
EVENT_COM_DATE,
EVENT_COM_STATUS)
VALUES (
SEQ_EVENT_COM_NO.NEXTVAL,
3,
2,
'오오오 참여해야겠어요',
SYSDATE,
DEFAULT);

INSERT INTO TB_EVENT_COMMENT(
EVENT_COM_NO,
EVENT_NO,
MEM_NO,
EVENT_COM_CONTENTS,
EVENT_COM_DATE,
EVENT_COM_STATUS)
VALUES (
SEQ_EVENT_COM_NO.NEXTVAL,
2,
4,
'좋은 이벤트네요~~~~!!',
SYSDATE,
DEFAULT);

INSERT INTO TB_EVENT_COMMENT(
EVENT_COM_NO,
EVENT_NO,
MEM_NO,
EVENT_COM_CONTENTS,
EVENT_COM_DATE,
EVENT_COM_STATUS)
VALUES (
SEQ_EVENT_COM_NO.NEXTVAL,
5,
1,
'이벤트 참여합니다 ㅎㅎㅎㅎ',
SYSDATE,
DEFAULT);

INSERT INTO TB_EVENT_COMMENT(
EVENT_COM_NO,
EVENT_NO,
MEM_NO,
EVENT_COM_CONTENTS,
EVENT_COM_DATE,
EVENT_COM_STATUS)
VALUES (
SEQ_EVENT_COM_NO.NEXTVAL,
4,
5,
'이벤트 참여할게요!',
SYSDATE,
DEFAULT);

INSERT INTO TB_WISHLIST VALUES(1,1);
INSERT INTO TB_WISHLIST VALUES(1,3);
INSERT INTO TB_WISHLIST VALUES(1,2);
INSERT INTO TB_WISHLIST VALUES(2,1);
INSERT INTO TB_WISHLIST VALUES(2,5);
INSERT INTO TB_WISHLIST VALUES(3,1);
INSERT INTO TB_WISHLIST VALUES(4,3);
INSERT INTO TB_WISHLIST VALUES(5,2);
-- 데이터 넣기(TB_ALLERGY)
INSERT INTO TB_ALLERGY
VALUES('A' || SEQ_ALG_NO.NEXTVAL,'난류');
INSERT INTO TB_ALLERGY
VALUES('A' || SEQ_ALG_NO.NEXTVAL,'우유');
INSERT INTO TB_ALLERGY
VALUES('A' || SEQ_ALG_NO.NEXTVAL,'곡류');
INSERT INTO TB_ALLERGY
VALUES('A' || SEQ_ALG_NO.NEXTVAL,'갑각류');
INSERT INTO TB_ALLERGY
VALUES('A' || SEQ_ALG_NO.NEXTVAL,'견과류');
-- 데이터 넣기(TB_MEM_ALLERGY)
INSERT INTO TB_MEM_ALLERGY VALUES (2,'A1');
INSERT INTO TB_MEM_ALLERGY VALUES (3,'A2');
INSERT INTO TB_MEM_ALLERGY VALUES (3,'A1');
INSERT INTO TB_MEM_ALLERGY VALUES (3,'A5');
INSERT INTO TB_MEM_ALLERGY VALUES (4,'A1');
INSERT INTO TB_MEM_ALLERGY VALUES (4,'A2');
INSERT INTO TB_MEM_ALLERGY VALUES (5,'A3');
INSERT INTO TB_MEM_ALLERGY VALUES (5,'A4');

COMMIT;